version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=paleta-api
      - POSTGRES_PASSWORD=paleta-api-password
      - POSTGRES_DB=paleta
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "paleta@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
      